<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicStore.Dto\MusicStore.Dto.csproj" />
    <ProjectReference Include="..\MusicStore.Persistence\MusicStore.Persistence.csproj" />
  </ItemGroup>

</Project>
